wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
dropout:
  desc: null
  value: 0.5
epochs:
  desc: null
  value: 3
lr:
  desc: null
  value: 0.001
num_classes:
  desc: null
  value: 53
pretrain_model:
  desc: null
  value: distilbert-base-uncased
